/* DECLARACIÓN DE SECUENCIAS Y OBTENCIÓN DE TAMAÑOS DE ESTAS.*/
import java.io.*;

public class AlineamientoMultipleSecuencias {

	private String[] secuencia;
	private int[] tamanyo;
	public int numeroSecuencias = 2;
	public int tamanyoGap;

	public AlineamientoMultipleSecuencias() {
		secuencia = new String[numeroSecuencias];

		// secuencia[0] =
		// "ATGTTCGCCGACCGCTGACTATTCTCTACAAACCACAAAGATATTGGAACACTA" +
		// "TACCTACTATTCGGCGCATGAGCTGGAGTCCTGGGCACAGCCCTAAGTCTCCTTA" +
		// "TTCGGGCTGAACTAGGCCAACCAGGCAACCTTCTAGGTAATGACCACATCTACAA" +
		// "TGTCATCGTCACAGCCCATGCATTCGTAATAATCTTCTTCATAGTAATGCCTATT" +
		// "ATAATCGGAGGCTTTGGCAACTGGCTAGTTCCCTTGATAATTGGTGCCCCCGACA" +
		// "TGGCATTCCCCCGCATAAACAACATAAGCTTCTGGCTCCTGCCCCCTTCTCTCCT" +
		// "ACTCCTACTTGCATCTGCCATAGTAGAAGCCGGCGCCGGAACAGGTTGAACAGTC" +
		// "TACCCTCCCTTAGCGGGAAACTACTCGCATCCTGGAGCCTCCGTAGACCTAACCA" +
		// "TCTTCTCCTTGCATCTGGCAGGCGTCTCCTCTATCCTAGGAGCCATTAACTTCAT" +
		// "CACAACAATTATTAATATAAAACCTCCTGCCATGACCCAATACCAAACACCCCTC" +
		// "TTCGTCTGATCCGTCCTAATCACAGCAGTCTTACTTCTCCTATCCCTCCCAGTCC" +
		// "TAGCTGCTGGCATCACCATACTATTGACAGATCGTAACCTCAACACTACCTTCTT" +
		// "CGACCCAGCCGGGGGAGGAGACCCTATTCTATATCAACACTTATTCTGATTTTTT" +
		// "GGCCACCCCGAAGTTTATATTCTTATCCTACCAGGCTTCGGAATAATTTCCCACA" +
		// "TTGTAACTTACTACTCCGGAAAAAAAGAACCATTTGGATATATAGGCATGGTTTG" +
		// "AGCTATAATATCAATTGGCTTCCTAGGGTTTATCGTGTGAGCACACCATATATTT" +
		// "ACAGTAGGAATAGACGTAGACACACGAGCCTATTTCACCTCCGCTACCATAATCA" +
		// "TTGCTATTCCTACCGGCGTCAAAGTATTCAGCTGACTCGCTACACTTCACGGAAG" +
		// "CAATATGAAATGATCTGCCGCAGTACTCTGAGCCCTAGGGTTTATCTTTCTCTTC" +
		// "ACCGTAGGTGGCCTAACCGGCATTGTACTAGCAAACTCATCATTAGACATCGTGC" +
		// "TACACGACACATACTACGTCGTAGCCCACTTCCACTATGTTCTATCAATAGGAGC" +
		// "TGTATTCGCCATCATAGGGGGCTTCATTCACTGATTCCCCCTATTCTCAGGCTAT" +
		// "ACCCTAGACCAAACCTATGCCAAAATCCAATTTGCCATCATGTTCATTGGCGTAA" +
		// "ACCTAACCTTCTTCCCACAACACTTCCTTGGCCTATCTGGGATGCCCCGACGTTA" +
		// "CTCGGACTACCCCGATGCATATACCACATGAAATGTCCTATCATCCGTAGGCTCA" +
		// "TTTATCTCCCTGACAGCAGTAATATTAATAATTTTCATGATTTGAGAAGCCTTTG" +
		// "CTTCAAAACGAAAAGTCCTAATAGTAGAAGAGCCCTCCACAAACCTGGAGTGACT" +
		// "ATATGGATGCCCCCCACCCTACCACACATTCGAAGAACCCGTATACATAAAATCT" +
		// "AGA";
		// secuencia[1] =
		// "CTCGGACTACCCCGATGCATATACCACATGAAATGTCCTATCATCCGTAGGCTCA" +
		// "TTTATCTCCCTGACAGCAGTAATATTAATAATTTTCATGATTTGAGAAGCCTTTG" +
		// "CTTCAAAACGAAAAGTCCTAATAGTAGAAGAGCCCTCCACAAACCTGGAGTGACT" +
		// "ATATGGATGCCCCCCACCCTACCACACATTCGAAGAACCCGTATACATAAAATCT" +
		// "AGA";

		secuencia[0] = "CTCGGACTACCCCGATGCATATACCACATGAAATGTCCTATCATCCGTAGGCTCA"
				+ "TTTATCTCCCTGACAGCAGTAATATTAATAATTTTCATGATTTGAGAAGCCTTTG"
				+ "CTTCAAAACGAAAAGTCCTAATAGTAGAAGAGCCCTCCACAAACCTGGAGTGACT"
				+ "ATATGGATGCCCCCCACCCTACCACACATTCGAAGAACCCGTATACATAAAATCT"
				+ "AGA";
		secuencia[1] = "CTCGGACTACCCCGATGCATATACCACATGAAATGTCCTATCATCCGTAGGCTCA"
				+ "TTTATCTCCCTGACAGCAGTAATATTAATAATTTTCATGATTTGAGAAGCCTTTG"
				+ "CTTCAAAACGAAAAGTCCTAATAGTAGAAGAGCCCTCCACAAACCTGGAGTGACT"
				+ "ATATGGATGCCCCCCACCCTACCACACATTCGAAGAACCCGTATACATAAAATCT"
				+ "AGA";

		// secuencia[0] = "CTCG";
		// secuencia[1] = "CACG";

		tamanyo = new int[numeroSecuencias];
		for (int i = 0; i < numeroSecuencias; i++) {
			tamanyo[i] = secuencia[i].length();
			if (tamanyo[i] > tamanyoGap)
				tamanyoGap = tamanyo[i];
		}
		tamanyoGap += 10;
	}

	public int length(int index) {
		return tamanyo[index];
	}

	public char getChar(int W, int L) {
		return secuencia[W].charAt(L);
	}

}
